import React, { createContext, useContext, useState } from "react";

const translations = {
  EN: {
    // ── HEADER ──────────────────────────────────────────────
    nav_products: "Products", nav_services: "Services", nav_software: "Software",
    nav_applications: "Applications", nav_learn: "Learn", nav_support: "Support",
    nav_contact: "Contact", find_reseller: "Find a Reseller",

    // ── FOOTER ──────────────────────────────────────────────
    enter_email: "Enter your email address for updates",
    email_placeholder: "Business email", copyright: "© MYACCESS 2026",
    privacy: "Privacy Policy", terms: "Terms of Service", faq: "FAQ",
    footer_3dprinters: "3D Printers", footer_postprocess: "Post-Processing",
    footer_materials: "Materials", footer_software: "Software",
    footer_industries: "Industries", footer_learn: "Learn",
    footer_company: "Company", footer_support: "Support", footer_sales: "Sales",

    // ── CONTACT PAGE ────────────────────────────────────────
    contact_title: "Get in touch with us",
    contact_sales_title: "Contact Sales",
    contact_sales_desc: "Our experts are ready to help you find the right automation solutions to scale your business efficiency around the world.",
    find_reseller_btn: "Find a Local Reseller >",
    contact_support_title: "Contact Support",
    contact_support_desc: "If you have questions about using our products, please check out our support resources or reach out to us below.",
    visit_support: "Visit Our Support Site >", create_ticket: "Create a Support Ticket >",
    contact_general_title: "Contact MYACCESS",
    contact_general_desc: "Want to share feedback on your MYACCESS experience with us? We're listening and ready to assist with general inquiries.",
    submit_feedback: "Submit Feedback >", offices: "Offices", show_on_map: "Show on Map >",

    // ── INDUSTRIES PAGE ─────────────────────────────────────
    ind_headline: "Precise and Versatile 3D Printing for Professionals Across Industries",
    ind_subtext: "Formlabs 3D printers are designed to help you excel in your industry, bringing the power of advanced stereolithography and selective laser sintering 3D printing to your business at a fraction of the cost of service bureaus or traditional industrial 3D printers.",
    select_industry: "Select Your Industry", learn_more: "Learn More",
    ind_banner_title: "Wondering how a 3D printer can help with your work?",
    ind_banner_sub: "Get a free consultation from an expert.",
    scaling_title: "Start Scaling Your Prototyping and Production Today",
    scaling_sub: "Explore our 3D printers to find the right solution for your business or contact a Formlabs 3D printing expert for a 1-1 consultation.",
    explore_printers: "Explore 3D Printers",
    ind_engineering: "Engineering", ind_manufacturing: "Manufacturing", ind_automotive: "Automotive",
    ind_aerospace: "Aerospace", ind_dental: "Dental", ind_medical: "Medical",
    ind_education: "Education", ind_entertainment: "Entertainment", ind_jewelry: "Jewelry", ind_audio: "Audio",

    // ── HOME PAGE ────────────────────────────────────────────
    home_hero_title: "Reinventing Ideas for Sustainability",
    home_hero_sub: "Where IoT, AI & Robotics Come Together",
    home_hero_btn1: "Explore Our Products", home_hero_btn2: "Explore Kiosk",
    ind_ems: "EMS", ind_robotics: "Robotics", ind_3dprint: "3D Print Farm",
    ind_ai: "Artificial Intelligence", ind_m2m: "Machine to Machine",
    ind_proddev: "Product Development", ind_allservices: "All Services",
    home_latest_news: "Latest News", learn_more_btn: "Learn More",
    home_feature_cat: "SMART SECURE SEAMLESS CONTROL SYSTEM",
    home_feature_title: "Transforming Shutter Access with Automation",
    home_feature_desc: "MySafeShutter is an automation system designed by MyAccess to improve the way rolling shutters are operated in shops, garages, and industrial spaces. By combining mechanical reliability with modern electronic control, the system enhances safety, convenience, and operational efficiency while supporting the growing need for automated access solutions.",
    home_news1_cat: "PROTOTYPE, PRINT, AND PRODUCE WITH PRECISION",
    home_news1_title: "3D Print Farm: Advanced 3D Printing For Prototyping And Production",
    home_news2_cat: "CENTRALIZED CONTROL FOR CONNECTED DEVICES",
    home_news2_title: "Smart Kiosk: Digital Control Center For Environment Control",
    home_news3_cat: "SMART WAY TO MANAGE BUSINESS IN ONE PLATFORM",
    home_news3_title: "Modular ERP: Structured Digital System For Business Management",
    home_read_all_news: "READ ALL NEWS >",
    home_solve_title: "Solve Complex Challenges",
    home_solve_sub: "with MyAccess expertise.",
    home_explore_services: "Explore all Services",
    home_biocompat: "BIOCOMPATIBLE Class I and Class II with Form 4B",
    home_make_anything: "Make Anything",
    home_make_anything_sub: "With MYACCESS Capabilities",
    tab_products: "Products", tab_auxiliary: "Auxiliary Products",
    tab_giveaway: "Giveaway Products", tab_lab: "Laboratory And Farms", tab_skill: "Skill Enhancement",
    home_rapid_title: "Rapid Prototyping",
    home_rapid_desc: "Turn your ideas into high-fidelity prototypes that look and work like final products within a day and bring better products to market faster.",
    home_watch_webinar: "WATCH THE WEBINAR NOW >",
    home_concept: "Concept Exploration", home_looks: "Looks-Like Prototyping",
    home_functional: "Functional Prototyping", home_validation: "Product Validation",
    home_get_in_touch: "Get In Touch",

    // ── ABOUT PAGE ───────────────────────────────────────────
    about_intro_title: "MyAccess Builds Natural Technology That Turns Ideas into Meaningful Solutions",
    about_intro_p1: "We want to change the perspective of technology to \"Natural Technology\". Our works purely justify that technology doesn't always kill nature. There is always at least a single problem to a solution. We find the problems even to our solutions and reshape the technology to its good side.",
    about_intro_p2: "In order to identify a problem, we first solve it in different ways and then identify different problems. This leaves a margin to gather problems and find an innovative solution that is ever-lasting.",
    about_who_title: "Who We Are",
    about_who_desc: "We as a team don't always have people. We also consider places, machines, thoughts, and things as a team because they help in completing us. We are a team in search of a community, who can lead their thoughts in serving every individual giving a broader scope of life to every individual and making technology the means to keep alive togetherness rather than distancing.",
    about_mission_title: "Our Mission",
    about_mission_desc: "Give each individual the quality of life and time they deserve for a lifetime.",
    about_vision_title: "Our Vision",
    about_vision_desc: "To be the world's best company shaping the technology more to its silver lining.",
    about_see_awards: "See More Awards",
    stat_projects: "Projects Completed", stat_clients: "Clients", stat_years: "Years Experience",
    about_strength1_title: "Strategy", about_strength1_desc: "Prioritize fresh talent rather than early talent without any bias. Youth has the power to make or destroy the weapon called technology.",
    about_strength2_title: "Tactic", about_strength2_desc: "Lending hands in the educational sector is the best tactic to explore and inject thoughts into one's mind.",
    about_strength3_title: "Goal", about_strength3_desc: "The main goal is to provide you with experience and wisdom rather than knowledge.",
    about_our_strength: "Our Strength",
    about_strength_desc: "At MYACCESS PRIVATE LIMITED, we believe every individual has the potential to make a significant impact, yet we embrace the power of teamwork, understanding that together, we achieve more. Our values are steadfast, guiding us reliably through all challenges.",
    about_our_leadership: "Our Leadership",
    leader1_role: "Founder", leader1_bio: "Surya is the visionary driving MYACCESS towards 'Natural Technology.' He focuses on solving complex problems by reshaping technology to align with nature and human needs.",
    leader2_role: "Co-Founder", leader2_bio: "Naveen leads the technical strategy, ensuring that every MYACCESS innovation is built with precision, scalability, and excellence to meet modern industrial demands.",
    about_advisory: "Our Advisory Committee",
    advisor1_role: "GPT Principal", advisor1_bio: "Dr. Shekar provides academic oversight and institutional guidance for cutting-edge research.", advisor1_detailed: "Principal of Government Polytechnic Pendurthi and seasoned Head of the Department at the Department of Technical Education, Andhra Pradesh, brings extensive expertise in Mechanical Engineering to MYACCESS Advisory Committee.",
    advisor2_role: "Professor", advisor2_bio: "With decades of experience, Dr. Krishna advises on technological curricula and student strategies.", advisor2_detailed: "Dr. B.T. Krishna, a Professor of Electronics and Communication Engineering at UCEK, JNTUK, brings expertise in Nanoelectronics and Analog VLSI to our Advisory Committee. An acclaimed scholar and a fellow of IEEE and IETE, his guidance is pivotal in steering MYACCESS PRIVATE LIMITED’s innovative endeavors.",
    advisor3_role: "Assistant Professor", advisor3_bio: "Dr. Chisti focuses on AI implementation and automation logic for robust systems.", advisor3_detailed: "Md Khwaja Moinuddin Chishty, an esteemed Advisory Committee member at MYACCESS PRIVATE LIMITED and Assistant Professor at GITAM University, is an award-winning inventor and expert in AI, machine learning, and embedded systems.",
    advisor4_role: "Associate Professor", advisor4_bio: "Dr. Rao leads our research initiatives in system optimization and sustainable technology.", advisor4_detailed: "Dr. Bhaskara Rao Jammu, an esteemed Advisory Committee member at MYACCESS PRIVATE LIMITED, is also an Associate Professor at GVP College of Engineering. Specializing in ASIC design and FPGA development.",
    about_frontline_title: "Our Frontline Team",
    about_frontline_desc: "At MYACCESS PRIVATE LIMITED, our team of experts leads the charge in technology innovation, harnessing AI, IoT, and automation to improve everyday life.",
    ft1_role: "Frontend & Embedded Developer", ft1_bio: "Builds responsive and dynamic user interfaces using React and develops embedded solutions for smart devices.",
    ft2_role: "Back-End Developer", ft2_bio: "Uses Django to build robust, scalable web applications with deep expertise in data-driven systems.",
    ft3_role: "Hardware Engineer", ft3_bio: "Validates performance and durability of our electronic products through comprehensive stress and functionality tests.",
    ft4_role: "Procurement Engineer", ft4_bio: "Plays a crucial role in sourcing and managing the services that support our technological innovations.",
    ft5_role: "Electronics Engineer", ft5_bio: "Core of our product development. Designs and implements circuitry and systems that power our innovative devices.",
    ft6_role: "Embedded Developer", ft6_bio: "Specializes in developing embedded systems, focusing on reliable hardware integration and efficient technology solutions.",
    ft7_role: "EMS Technician", ft7_bio: "Handles electronic manufacturing and system assembly, ensuring precise component integration and reliable electronic solutions.",
    ft8_role: "Cloud Engineer", ft8_bio: "Builds and manages scalable cloud infrastructure, ensuring secure, reliable, and high-performance systems for modern applications.",
    ft9_role: "Front-End Developer", ft9_bio: "Creates modern, responsive web interfaces focused on performance, usability, and seamless user experience.",
    about_commitment_title: "Our Commitment",
    about_commitment_desc: "At MYACCESS PRIVATE LIMITED, we champion unconventional thinking, urging our team to \"think crazy, not different\" as we believe unique ideas drive progress. We prioritize identifying and solving problems, upholding a strong commitment to excellence and integrity in everything we do.",
    about_community_btn: "Explore Community and Impact Initiatives",
  },

  HI: {
    // ── HEADER ──────────────────────────────────────────────
    nav_products: "उत्पाद", nav_services: "सेवाएं", nav_software: "सॉफ़्टवेयर",
    nav_applications: "अनुप्रयोग", nav_learn: "सीखें", nav_support: "सहायता",
    nav_contact: "संपर्क", find_reseller: "रीसेलर खोजें",

    // ── FOOTER ──────────────────────────────────────────────
    enter_email: "अपडेट के लिए ईमेल दर्ज करें",
    email_placeholder: "व्यावसायिक ईमेल", copyright: "© MYACCESS 2026",
    privacy: "गोपनीयता नीति", terms: "सेवा की शर्तें", faq: "सामान्य प्रश्न",
    footer_3dprinters: "3D प्रिंटर", footer_postprocess: "पोस्ट-प्रोसेसिंग",
    footer_materials: "सामग्री", footer_software: "सॉफ़्टवेयर",
    footer_industries: "उद्योग", footer_learn: "सीखें",
    footer_company: "कंपनी", footer_support: "सहायता", footer_sales: "बिक्री",

    // ── CONTACT PAGE ────────────────────────────────────────
    contact_title: "हमसे संपर्क करें",
    contact_sales_title: "बिक्री से संपर्क करें",
    contact_sales_desc: "हमारे विशेषज्ञ आपको सही समाधान खोजने में मदद करने के लिए तैयार हैं।",
    find_reseller_btn: "स्थानीय रीसेलर खोजें >",
    contact_support_title: "सहायता से संपर्क करें",
    contact_support_desc: "उत्पादों के बारे में प्रश्न हैं तो हमारे सहायता संसाधन देखें।",
    visit_support: "हमारी सहायता साइट देखें >", create_ticket: "सहायता टिकट बनाएं >",
    contact_general_title: "MYACCESS से संपर्क करें",
    contact_general_desc: "अपना फीडबैक साझा करना चाहते हैं? हम सुन रहे हैं।",
    submit_feedback: "फीडबैक सबमिट करें >", offices: "कार्यालय", show_on_map: "नक्शे पर दिखाएं >",

    // ── INDUSTRIES PAGE ─────────────────────────────────────
    ind_headline: "उद्योग पेशेवरों के लिए सटीक 3D प्रिंटिंग",
    ind_subtext: "Formlabs 3D प्रिंटर आपके उद्योग में उत्कृष्टता के लिए डिज़ाइन किए गए हैं।",
    select_industry: "अपना उद्योग चुनें", learn_more: "और जानें",
    ind_banner_title: "क्या 3D प्रिंटर आपके काम में मदद कर सकता है?",
    ind_banner_sub: "किसी विशेषज्ञ से निःशुल्क परामर्श प्राप्त करें।",
    scaling_title: "आज ही प्रोटोटाइपिंग शुरू करें",
    scaling_sub: "अपने व्यवसाय के लिए सही समाधान खोजने के लिए हमारे 3D प्रिंटर देखें।",
    explore_printers: "3D प्रिंटर देखें",
    ind_engineering: "इंजीनियरिंग", ind_manufacturing: "विनिर्माण", ind_automotive: "ऑटोमोटिव",
    ind_aerospace: "एयरोस्पेस", ind_dental: "दंत चिकित्सा", ind_medical: "चिकित्सा",
    ind_education: "शिक्षा", ind_entertainment: "मनोरंजन", ind_jewelry: "आभूषण", ind_audio: "ऑडियो",

    // ── HOME PAGE ────────────────────────────────────────────
    home_hero_title: "स्थिरता के लिए विचारों को नया रूप देना",
    home_hero_sub: "जहां IoT, AI और रोबोटिक्स एक साथ आते हैं",
    home_hero_btn1: "हमारे उत्पाद देखें", home_hero_btn2: "कियोस्क देखें",
    ind_ems: "EMS", ind_robotics: "रोबोटिक्स", ind_3dprint: "3D प्रिंट फार्म",
    ind_ai: "कृत्रिम बुद्धिमत्ता", ind_m2m: "मशीन टू मशीन",
    ind_proddev: "उत्पाद विकास", ind_allservices: "सभी सेवाएं",
    home_latest_news: "ताज़ा खबर", learn_more_btn: "और जानें",
    home_feature_cat: "स्मार्ट सुरक्षित नियंत्रण प्रणाली",
    home_feature_title: "स्वचालन के साथ शटर एक्सेस में बदलाव",
    home_feature_desc: "MySafeShutter एक स्वचालन प्रणाली है जिसे MyAccess ने दुकानों, गैरेज और औद्योगिक स्थानों में रोलिंग शटर को बेहतर बनाने के लिए डिज़ाइन किया है।",
    home_news1_cat: "सटीकता के साथ प्रोटोटाइप, प्रिंट और उत्पादन",
    home_news1_title: "3D प्रिंट फार्म: प्रोटोटाइपिंग और उत्पादन के लिए उन्नत 3D प्रिंटिंग",
    home_news2_cat: "कनेक्टेड डिवाइसों के लिए केंद्रीकृत नियंत्रण",
    home_news2_title: "स्मार्ट कियोस्क: पर्यावरण नियंत्रण के लिए डिजिटल नियंत्रण केंद्र",
    home_news3_cat: "एक प्लेटफॉर्म में व्यवसाय प्रबंधन का स्मार्ट तरीका",
    home_news3_title: "मॉड्यूलर ERP: व्यवसाय प्रबंधन के लिए डिजिटल प्रणाली",
    home_read_all_news: "सभी समाचार पढ़ें >",
    home_solve_title: "जटिल चुनौतियां सुलझाएं",
    home_solve_sub: "MyAccess विशेषज्ञता के साथ।",
    home_explore_services: "सभी सेवाएं देखें",
    home_biocompat: "Form 4B के साथ Class I और Class II बायोकम्पैटिबल",
    home_make_anything: "कुछ भी बनाएं",
    home_make_anything_sub: "MYACCESS क्षमताओं के साथ",
    tab_products: "उत्पाद", tab_auxiliary: "सहायक उत्पाद",
    tab_giveaway: "उपहार उत्पाद", tab_lab: "प्रयोगशाला और फार्म", tab_skill: "कौशल वृद्धि",
    home_rapid_title: "रैपिड प्रोटोटाइपिंग",
    home_rapid_desc: "अपने विचारों को एक दिन में उच्च-निष्ठा प्रोटोटाइप में बदलें और बेहतर उत्पाद तेज़ी से बाज़ार में लाएं।",
    home_watch_webinar: "वेबिनार अभी देखें >",
    home_concept: "अवधारणा अन्वेषण", home_looks: "दिखने वाला प्रोटोटाइप",
    home_functional: "कार्यात्मक प्रोटोटाइप", home_validation: "उत्पाद सत्यापन",
    home_get_in_touch: "संपर्क करें",

    // ── ABOUT PAGE ───────────────────────────────────────────
    about_intro_title: "MyAccess प्राकृतिक तकनीक बनाता है जो विचारों को सार्थक समाधानों में बदलती है",
    about_intro_p1: "हम प्रौद्योगिकी के दृष्टिकोण को \"प्राकृतिक प्रौद्योगिकी\" में बदलना चाहते हैं। हमारे काम यह साबित करते हैं कि प्रौद्योगिकी हमेशा प्रकृति को नुकसान नहीं पहुंचाती।",
    about_intro_p2: "किसी समस्या की पहचान करने के लिए, हम पहले उसे अलग-अलग तरीकों से हल करते हैं और फिर अलग-अलग समस्याओं की पहचान करते हैं।",
    about_who_title: "हम कौन हैं",
    about_who_desc: "हम एक ऐसी टीम हैं जो एक समुदाय की तलाश में है, जो अपने विचारों से हर व्यक्ति की सेवा कर सके।",
    about_mission_title: "हमारा मिशन",
    about_mission_desc: "हर व्यक्ति को जीवनभर के लिए जीवन की गुणवत्ता और समय देना।",
    about_vision_title: "हमारी दृष्टि",
    about_vision_desc: "दुनिया की सर्वश्रेष्ठ कंपनी बनना जो प्रौद्योगिकी को उसके अच्छे पक्ष की ओर आकार देती है।",
    about_see_awards: "और पुरस्कार देखें",
    stat_projects: "पूर्ण परियोजनाएं", stat_clients: "ग्राहक", stat_years: "वर्षों का अनुभव",
    about_strength1_title: "रणनीति", about_strength1_desc: "बिना किसी पूर्वाग्रह के नई प्रतिभाओं को प्राथमिकता दें। युवाओं में प्रौद्योगिकी को बनाने या नष्ट करने की शक्ति है।",
    about_strength2_title: "युक्ति", about_strength2_desc: "शैक्षणिक क्षेत्र में मदद करना विचारों को खोजने और मन में डालने का सबसे अच्छा तरीका है।",
    about_strength3_title: "लक्ष्य", about_strength3_desc: "मुख्य लक्ष्य ज्ञान के बजाय अनुभव और ज्ञान प्रदान करना है।",
    about_our_strength: "हमारी शक्ति",
    about_strength_desc: "MYACCESS PRIVATE LIMITED में, हम मानते हैं कि हर व्यक्ति में महत्वपूर्ण प्रभाव डालने की क्षमता है, फिर भी हम टीमवर्क की शक्ति को अपनाते हैं।",
    about_our_leadership: "हमारा नेतृत्व",
    leader1_role: "संस्थापक", leader1_bio: "सूर्य MYACCESS को 'प्राकृतिक प्रौद्योगिकी' की ओर ले जाने वाले दूरदर्शी हैं।",
    leader2_role: "सह-संस्थापक", leader2_bio: "नवीन तकनीकी रणनीति का नेतृत्व करते हैं, यह सुनिश्चित करते हुए कि हर MYACCESS नवाचार सटीकता के साथ बनाया गया है।",
    about_advisory: "हमारी सलाहकार समिति",
    advisor1_role: "GPT प्रधानाचार्य", advisor1_bio: "डॉ. शेखर अत्याधुनिक अनुसंधान के लिए शैक्षणिक देखरेख प्रदान करते हैं।", advisor1_detailed: "Government Polytechnic Pendurthi के प्रधानाचार्य और आंध्र प्रदेश में तकनीकी शिक्षा विभाग के अनुभवी HOD।",
    advisor2_role: "प्रोफेसर", advisor2_bio: "दशकों के अनुभव के साथ, डॉ. कृष्णा तकनीकी पाठ्यक्रम पर सलाह देते हैं।", advisor2_detailed: "UCEK, JNTUK में इलेक्ट्रॉनिक्स और संचार इंजीनियरिंग के प्रोफेसर, नैनोइलेक्ट्रॉनिक्स में विशेषज्ञ।",
    advisor3_role: "सहायक प्रोफेसर", advisor3_bio: "डॉ. चिश्ती AI कार्यान्वयन और स्वचालन तर्क पर ध्यान केंद्रित करते हैं।", advisor3_detailed: "GITAM University में AI, मशीन लर्निंग और एम्बेडेड सिस्टम के विशेषज्ञ।",
    advisor4_role: "एसोसिएट प्रोफेसर", advisor4_bio: "डॉ. राव सिस्टम अनुकूलन में हमारी अनुसंधान पहल का नेतृत्व करते हैं।", advisor4_detailed: "GVP College of Engineering में एसोसिएट प्रोफेसर, ASIC डिजाइन और FPGA विकास में विशेषज्ञ।",
    about_frontline_title: "हमारी अग्रिम पंक्ति टीम",
    about_frontline_desc: "MYACCESS PRIVATE LIMITED में, हमारी विशेषज्ञों की टीम AI, IoT और स्वचालन का उपयोग करके रोजमर्रा की जिंदगी को बेहतर बनाती है।",
    ft1_role: "फ्रंटएंड और एम्बेडेड डेवलपर", ft1_bio: "React का उपयोग करके responsive इंटरफेस और स्मार्ट डिवाइसों के लिए एम्बेडेड समाधान बनाते हैं।",
    ft2_role: "बैक-एंड डेवलपर", ft2_bio: "Django का उपयोग करके robust, scalable वेब एप्लिकेशन बनाते हैं।",
    ft3_role: "हार्डवेयर इंजीनियर", ft3_bio: "व्यापक परीक्षणों के माध्यम से हमारे इलेक्ट्रॉनिक उत्पादों के प्रदर्शन और स्थायित्व को मान्य करते हैं।",
    ft4_role: "खरीद इंजीनियर", ft4_bio: "हमारी तकनीकी नवाचारों का समर्थन करने वाली सेवाओं को सोर्स और प्रबंधित करने में महत्वपूर्ण भूमिका निभाते हैं।",
    ft5_role: "इलेक्ट्रॉनिक्स इंजीनियर", ft5_bio: "उत्पाद विकास के मूल में हैं। हमारे नवीन उपकरणों को शक्ति देने वाले सर्किटरी और सिस्टम डिज़ाइन करते हैं।",
    ft6_role: "एम्बेडेड डेवलपर", ft6_bio: "एम्बेडेड सिस्टम विकसित करने में विशेषज्ञ, हार्डवेयर एकीकरण और कुशल तकनीकी समाधानों पर ध्यान केंद्रित करते हैं।",
    ft7_role: "EMS तकनीशियन", ft7_bio: "इलेक्ट्रॉनिक विनिर्माण और सिस्टम असेंबली संभालते हैं, सटीक घटक एकीकरण सुनिश्चित करते हैं।",
    ft8_role: "क्लाउड इंजीनियर", ft8_bio: "आधुनिक अनुप्रयोगों के लिए सुरक्षित, विश्वसनीय और उच्च-प्रदर्शन प्रणाली सुनिश्चित करते हुए scalable cloud infrastructure बनाते हैं।",
    ft9_role: "फ्रंट-एंड डेवलपर", ft9_bio: "प्रदर्शन, उपयोगिता और seamless उपयोगकर्ता अनुभव पर केंद्रित आधुनिक, responsive वेब इंटरफेस बनाते हैं।",
    about_commitment_title: "हमारी प्रतिबद्धता",
    about_commitment_desc: "MYACCESS PRIVATE LIMITED में, हम अपरंपरागत सोच का समर्थन करते हैं, अपनी टीम को \"पागल सोचो, अलग नहीं\" के लिए प्रोत्साहित करते हैं क्योंकि हमें विश्वास है कि अनूठे विचार प्रगति को प्रेरित करते हैं।",
    about_community_btn: "सामुदायिक और प्रभाव पहलों का अन्वेषण करें",
  },

  TA: {
    // ── HEADER ──────────────────────────────────────────────
    nav_products: "தயாரிப்புகள்", nav_services: "சேவைகள்", nav_software: "மென்பொருள்",
    nav_applications: "பயன்பாடுகள்", nav_learn: "கற்றுக்கொள்", nav_support: "ஆதரவு",
    nav_contact: "தொடர்பு", find_reseller: "மறுவிற்பனையாளரை கண்டறியுங்கள்",

    // ── FOOTER ──────────────────────────────────────────────
    enter_email: "புதுப்பிப்புகளுக்கு மின்னஞ்சல் உள்ளிடுங்கள்",
    email_placeholder: "வணிக மின்னஞ்சல்", copyright: "© MYACCESS 2026",
    privacy: "தனியுரிமை கொள்கை", terms: "சேவை விதிமுறைகள்", faq: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    footer_3dprinters: "3D அச்சுப்பொறிகள்", footer_postprocess: "பிந்தைய செயலாக்கம்",
    footer_materials: "பொருட்கள்", footer_software: "மென்பொருள்",
    footer_industries: "தொழில்கள்", footer_learn: "கற்றுக்கொள்",
    footer_company: "நிறுவனம்", footer_support: "ஆதரவு", footer_sales: "விற்பனை",

    // ── CONTACT PAGE ────────────────────────────────────────
    contact_title: "எங்களை தொடர்பு கொள்ளுங்கள்",
    contact_sales_title: "விற்பனையை தொடர்பு கொள்ளுங்கள்",
    contact_sales_desc: "உங்கள் வணிகத்திற்கு சரியான தீர்வுகளை கண்டறிய எங்கள் நிபுணர்கள் தயாராக உள்ளனர்.",
    find_reseller_btn: "உள்ளூர் மறுவிற்பனையாளரை கண்டறியுங்கள் >",
    contact_support_title: "ஆதரவை தொடர்பு கொள்ளுங்கள்",
    contact_support_desc: "தயாரிப்புகளை பயன்படுத்துவதில் கேள்விகள் இருந்தால், எங்கள் ஆதரவு ஆதாரங்களை பார்க்கவும்.",
    visit_support: "எங்கள் ஆதரவு தளத்தை பார்வையிடுங்கள் >", create_ticket: "ஆதரவு டிக்கெட் உருவாக்கவும் >",
    contact_general_title: "MYACCESS ஐ தொடர்பு கொள்ளுங்கள்",
    contact_general_desc: "உங்கள் கருத்தை பகிர விரும்புகிறீர்களா? நாங்கள் கேட்கிறோம்.",
    submit_feedback: "கருத்தை சமர்ப்பிக்கவும் >", offices: "அலுவலகங்கள்", show_on_map: "வரைபடத்தில் காட்டு >",

    // ── INDUSTRIES PAGE ─────────────────────────────────────
    ind_headline: "தொழில் வல்லுநர்களுக்கான துல்லியமான 3D அச்சிடல்",
    ind_subtext: "Formlabs 3D அச்சுப்பொறிகள் உங்கள் தொழிலில் சிறந்து விளங்க வடிவமைக்கப்பட்டுள்ளன.",
    select_industry: "உங்கள் தொழிலை தேர்ந்தெடுங்கள்", learn_more: "மேலும் அறியுங்கள்",
    ind_banner_title: "3D அச்சுப்பொறி உங்கள் பணிக்கு உதவுமா?",
    ind_banner_sub: "நிபுணரிடம் இலவச ஆலோசனை பெறுங்கள்.",
    scaling_title: "இன்றே உங்கள் உற்பத்தியை அளவிடத் தொடங்குங்கள்",
    scaling_sub: "உங்கள் வணிகத்திற்கு சரியான தீர்வை கண்டறிய எங்கள் 3D அச்சுப்பொறிகளை ஆராயுங்கள்.",
    explore_printers: "3D அச்சுப்பொறிகளை ஆராயுங்கள்",
    ind_engineering: "பொறியியல்", ind_manufacturing: "உற்பத்தி", ind_automotive: "வாகனம்",
    ind_aerospace: "வான்வெளி", ind_dental: "பல் மருத்துவம்", ind_medical: "மருத்துவம்",
    ind_education: "கல்வி", ind_entertainment: "பொழுதுபோக்கு", ind_jewelry: "நகைகள்", ind_audio: "ஒலி",

    // ── HOME PAGE ────────────────────────────────────────────
    home_hero_title: "நிலைத்தன்மைக்காக யோசனைகளை மறுவடிவமைத்தல்",
    home_hero_sub: "IoT, AI மற்றும் ரோபாட்டிக்ஸ் ஒன்றாக வரும் இடம்",
    home_hero_btn1: "எங்கள் தயாரிப்புகளை ஆராயுங்கள்", home_hero_btn2: "கியோஸ்க் ஆராயுங்கள்",
    ind_ems: "EMS", ind_robotics: "ரோபாட்டிக்ஸ்", ind_3dprint: "3D பிரிண்ட் பண்ணை",
    ind_ai: "செயற்கை நுண்ணறிவு", ind_m2m: "இயந்திரம் முதல் இயந்திரம்",
    ind_proddev: "தயாரிப்பு மேம்பாடு", ind_allservices: "அனைத்து சேவைகள்",
    home_latest_news: "சமீபத்திய செய்திகள்", learn_more_btn: "மேலும் அறியுங்கள்",
    home_feature_cat: "ஸ்மார்ட் பாதுகாப்பான கட்டுப்பாட்டு அமைப்பு",
    home_feature_title: "தானியங்கியுடன் ஷட்டர் அணுகலை மாற்றுதல்",
    home_feature_desc: "MySafeShutter என்பது MyAccess ஆல் வடிவமைக்கப்பட்ட ஒரு தானியங்கி அமைப்பு.",
    home_news1_cat: "துல்லியத்துடன் மாதிரி, அச்சிடு மற்றும் உற்பத்தி செய்யுங்கள்",
    home_news1_title: "3D பிரிண்ட் பண்ணை: மேம்பட்ட 3D அச்சிடல்",
    home_news2_cat: "இணைக்கப்பட்ட சாதனங்களுக்கு மையப்படுத்தப்பட்ட கட்டுப்பாடு",
    home_news2_title: "ஸ்மார்ட் கியோஸ்க்: சுற்றுச்சூழல் கட்டுப்பாடு மையம்",
    home_news3_cat: "ஒரு தளத்தில் வணிகத்தை நிர்வகிக்க ஸ்மார்ட் வழி",
    home_news3_title: "மட்டு ERP: வணிக நிர்வாகத்திற்கான கட்டமைக்கப்பட்ட டிஜிட்டல் அமைப்பு",
    home_read_all_news: "அனைத்து செய்திகளையும் படியுங்கள் >",
    home_solve_title: "சிக்கலான சவால்களை தீர்க்கவும்",
    home_solve_sub: "MyAccess நிபுணத்துவத்துடன்.",
    home_explore_services: "அனைத்து சேவைகளையும் ஆராயுங்கள்",
    home_biocompat: "Form 4B உடன் Class I மற்றும் Class II உயிரியல் இணக்கம்",
    home_make_anything: "எதையும் உருவாக்குங்கள்",
    home_make_anything_sub: "MYACCESS திறன்களுடன்",
    tab_products: "தயாரிப்புகள்", tab_auxiliary: "துணை தயாரிப்புகள்",
    tab_giveaway: "பரிசு தயாரிப்புகள்", tab_lab: "ஆய்வகம் மற்றும் பண்ணைகள்", tab_skill: "திறன் மேம்பாடு",
    home_rapid_title: "விரைவு மாதிரியாக்கம்",
    home_rapid_desc: "உங்கள் யோசனைகளை ஒரு நாளில் உயர்தர மாதிரிகளாக மாற்றி சந்தையில் வேகமாக கொண்டு வாருங்கள்.",
    home_watch_webinar: "வெபினரை இப்போது பாருங்கள் >",
    home_concept: "கருத்து ஆய்வு", home_looks: "தோற்ற மாதிரியாக்கம்",
    home_functional: "செயல்பாட்டு மாதிரியாக்கம்", home_validation: "தயாரிப்பு சரிபார்ப்பு",
    home_get_in_touch: "தொடர்பு கொள்ளுங்கள்",

    // ── ABOUT PAGE ───────────────────────────────────────────
    about_intro_title: "MyAccess இயற்கை தொழில்நுட்பத்தை உருவாக்குகிறது",
    about_intro_p1: "நாங்கள் தொழில்நுட்பத்தின் கண்ணோட்டத்தை 'இயற்கை தொழில்நுட்பமாக' மாற்ற விரும்புகிறோம்.",
    about_intro_p2: "ஒரு சிக்கலை அடையாளம் காண, நாங்கள் முதலில் அதை வெவ்வேறு வழிகளில் தீர்க்கிறோம்.",
    about_who_title: "நாங்கள் யார்",
    about_who_desc: "நாங்கள் ஒரு சமூகத்தை தேடும் குழு, எல்லா தனிநபர்களுக்கும் சேவை செய்ய தங்கள் எண்ணங்களை வழிநடத்தக்கூடியவர்கள்.",
    about_mission_title: "எங்கள் நோக்கம்",
    about_mission_desc: "ஒவ்வொரு தனிநபருக்கும் வாழ்நாள் முழுவதும் அவர்கள் தகுதியான வாழ்க்கை தரம் மற்றும் நேரம் வழங்குங்கள்.",
    about_vision_title: "எங்கள் தொலைநோக்கு",
    about_vision_desc: "தொழில்நுட்பத்தை அதன் நல்ல பக்கத்தை நோக்கி வடிவமைக்கும் உலகின் சிறந்த நிறுவனமாக இருக்க வேண்டும்.",
    about_see_awards: "மேலும் விருதுகளைப் பாருங்கள்",
    stat_projects: "முடிக்கப்பட்ட திட்டங்கள்", stat_clients: "வாடிக்கையாளர்கள்", stat_years: "ஆண்டுகள் அனுபவம்",
    about_strength1_title: "உத்தி", about_strength1_desc: "எந்த சார்பும் இல்லாமல் புதிய திறமைகளுக்கு முன்னுரிமை கொடுங்கள்.",
    about_strength2_title: "தந்திரம்", about_strength2_desc: "கல்வி துறையில் உதவுவது எண்ணங்களை மனதில் ஆராய்ந்து செலுத்த சிறந்த வழி.",
    about_strength3_title: "இலக்கு", about_strength3_desc: "முக்கிய இலக்கு அறிவை விட அனுபவம் மற்றும் ஞானம் வழங்குவது.",
    about_our_strength: "எங்கள் பலம்",
    about_strength_desc: "MYACCESS PRIVATE LIMITED இல், ஒவ்வொரு தனிநபருக்கும் குறிப்பிடத்தக்க தாக்கத்தை ஏற்படுத்தும் திறன் இருப்பதாக நம்புகிறோம்.",
    about_our_leadership: "எங்கள் தலைமை",
    leader1_role: "நிறுவனர்", leader1_bio: "Surya MYACCESS ஐ 'இயற்கை தொழில்நுட்பம்' நோக்கி வழிநடத்தும் தொலைநோக்காளர்.",
    leader2_role: "இணை நிறுவனர்", leader2_bio: "Naveen தொழில்நுட்ப உத்தியை வழிநடத்துகிறார், ஒவ்வொரு MYACCESS கண்டுபிடிப்பும் துல்லியத்துடன் கட்டமைக்கப்படுவதை உறுதிசெய்கிறார்.",
    about_advisory: "எங்கள் ஆலோசனைக் குழு",
    advisor1_role: "GPT முதல்வர்", advisor1_bio: "டாக்டர் Shekar அத்யாவசிய ஆராய்ச்சிக்கு கல்வி மேற்பார்வை வழங்குகிறார்.", advisor1_detailed: "Government Polytechnic Pendurthi முதல்வர் மற்றும் ஆந்திரப் பிரதேசத்தில் தொழில்நுட்ப கல்வி துறையின் HOD.",
    advisor2_role: "பேராசிரியர்", advisor2_bio: "பல தசாப்தங்களின் அனுபவத்துடன், டாக்டர் கிருஷ்ணா தொழில்நுட்ப பாடத்திட்டங்களில் ஆலோசனை வழங்குகிறார்.", advisor2_detailed: "UCEK, JNTUK இல் மின்னணு மற்றும் தகவல் தொடர்பு பொறியியல் பேராசிரியர்.",
    advisor3_role: "உதவி பேராசிரியர்", advisor3_bio: "டாக்டர் Chisti AI செயல்படுத்தல் மற்றும் தானியங்கி தர்க்கத்தில் கவனம் செலுத்துகிறார்.", advisor3_detailed: "GITAM பல்கலைக்கழகத்தில் AI, மெஷின் லேர்னிங் மற்றும் எம்பெடட் சிஸ்டம்களில் நிபுணர்.",
    advisor4_role: "இணை பேராசிரியர்", advisor4_bio: "டாக்டர் Rao அமைப்பு உகப்பாக்கத்தில் எங்கள் ஆராய்ச்சி முயற்சிகளை வழிநடத்துகிறார்.", advisor4_detailed: "GVP College of Engineering இல் இணை பேராசிரியர், ASIC வடிவமைப்பில் நிபுணர்.",
    about_frontline_title: "எங்கள் முன்னணி குழு",
    about_frontline_desc: "MYACCESS PRIVATE LIMITED இல், எங்கள் நிபுணர்கள் குழு AI, IoT மற்றும் தானியங்கியைப் பயன்படுத்தி அன்றாட வாழ்க்கையை மேம்படுத்துகிறது.",
    ft1_role: "ஃப்ரண்டெண்ட் மற்றும் எம்பெடட் டெவலப்பர்", ft1_bio: "React ஐ பயன்படுத்தி responsive இடைமுகங்கள் மற்றும் ஸ்மார்ட் சாதனங்களுக்கு எம்பெடட் தீர்வுகளை உருவாக்குகிறார்.",
    ft2_role: "பேக்-எண்ட் டெவலப்பர்", ft2_bio: "Django ஐ பயன்படுத்தி robust, scalable வலை பயன்பாடுகளை உருவாக்குகிறார்.",
    ft3_role: "வன்பொருள் பொறியாளர்", ft3_bio: "விரிவான சோதனைகள் மூலம் எங்கள் மின்னணு தயாரிப்புகளின் செயல்திறனை சரிபார்க்கிறார்.",
    ft4_role: "கொள்முதல் பொறியாளர்", ft4_bio: "எங்கள் தொழில்நுட்ப கண்டுபிடிப்புகளை ஆதரிக்கும் சேவைகளை சோர்ஸ் செய்வதில் முக்கிய பங்கு வகிக்கிறார்.",
    ft5_role: "மின்னணு பொறியாளர்", ft5_bio: "எங்கள் கண்டுபிடிப்பு சாதனங்களுக்கு சக்தி அளிக்கும் சர்க்யூட்ரி மற்றும் அமைப்புகளை வடிவமைக்கிறார்.",
    ft6_role: "எம்பெடட் டெவலப்பர்", ft6_bio: "எம்பெடட் சிஸ்டம்கள் உருவாக்குவதில் நிபுணர், வன்பொருள் ஒருங்கிணைப்பில் கவனம் செலுத்துகிறார்.",
    ft7_role: "EMS தொழில்நுட்பவியலாளர்", ft7_bio: "மின்னணு உற்பத்தி மற்றும் சிஸ்டம் அசம்பிளியை கையாள்கிறார்.",
    ft8_role: "கிளவுட் பொறியாளர்", ft8_bio: "நவீன பயன்பாடுகளுக்கு பாதுகாப்பான, நம்பகமான கிளவுட் உள்கட்டமைப்பை உருவாக்குகிறார்.",
    ft9_role: "ஃப்ரண்ட்-எண்ட் டெவலப்பர்", ft9_bio: "செயல்திறன், பயன்பாட்டு தன்மை மற்றும் seamless பயனர் அனுபவத்தில் கவனம் செலுத்தும் நவீன வலை இடைமுகங்களை உருவாக்குகிறார்.",
    about_commitment_title: "எங்கள் அர்ப்பணிப்பு",
    about_commitment_desc: "MYACCESS PRIVATE LIMITED இல், நாங்கள் மரபுக்கு மாறான சிந்தனையை ஆதரிக்கிறோம், எங்கள் குழுவை 'வித்தியாசமாக அல்ல, பைத்தியமாக சிந்திக்க' ஊக்குவிக்கிறோம்.",
    about_community_btn: "சமூக மற்றும் தாக்கம் முயற்சிகளை ஆராயுங்கள்",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("EN");
  const t = (key) => translations[lang]?.[key] ?? translations["EN"]?.[key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
